name: Deploy Documentation

on:
  push:
    branches:
      - master  # Adjust if your main branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and deploy
        run: |
          mkdir -p docs # Create a docs folder if not exists
          # Replace the build command with your actual documentation build command
          # For example, if you're using MkDocs:
          # mkdocs build -d docs
          echo "Build your documentation here"
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add docs
          git commit -m "Auto-update documentation [skip ci]"
          git push origin master:master
