on:
    push:
      # Sequence of patterns matched against refs/tags
      tags:
        - '*' # Push events to matching v*, i.e. v1.0, v20.15.10
  
name: Create Release
  
jobs:
    build:
      name: Create Release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Generate Changelog
          run: |
            # Install git-chglog
            curl -sSL https://install.git.chglog.io | sh
            
            # Get the last tag
            last_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
            
            # Generate changelog since the last tag
            git-chglog --output CHANGELOG.md --next-tag $last_tag
  
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.PAT_FOR_RELEASES }} # This token is provided by Actions, you do not need to create your own token
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            body: |
              $(cat CHANGELOG.md) # Include the generated changelog in the release body
  